services:

  dicecup:
    container_name: dicecup
    image: dicecup-image:latest
    network_mode: host
  #    ports:
  #      - 9002:9002

  field:
    container_name: field
    image: field-image:latest
    network_mode: host
  #    ports:
  #      - 9001:9001

  fileIO:
    container_name: fileIO
    image: fileio-image:latest
    network_mode: host
  #    ports:
  #      - 9000:9000

  game:
    container_name: game
    image: game-image:latest
    network_mode: host
  #    ports:
  #      - 9003:9003

  restcontroller:
    container_name: restcontroller
    image: restcontroller-image:latest
    network_mode: host
#    ports:
#      - 9006:9006

  tui:
    container_name: tui
    image: tui-image:latest
    network_mode: host
    stdin_open: true
    tty: true
#    ports:
#      - 9005:9005

  gui:
    container_name: gui
    image: gui-image:latest
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: ${DISPLAY}
#    ports:
#      - 9004:9004

  postgres:
    container_name: kniffel-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: kniffel_postgres
      POSTGRES_USER: kniffeldbuser
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: host

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres: