name: Scala CI

on:
  push:
    branches:
      - main
      - 'SARCH-*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: compile
        run: sbt compile
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt "; project field; +clean; +coverage; +test; +coverageReport"
          sbt "; project dicecup; +clean; +coverage; +test; +coverageReport"
          sbt "; project persistence; +clean; +coverage; +test; +coverageReport"
          sbt "; project game; +clean; +coverage; +test; +coverageReport"
          sbt "; project restcontroller; +clean; +coverage; +test; +coverageReport"
      - name: Create Coverage Report
        run: |
          sbt "; project field; coverageAggregate; coveralls"
          sbt "; project dicecup; coverageAggregate; coveralls"
          sbt "; project persistence; coverageAggregate; coveralls"        
          sbt "; project game; coverageAggregate; coveralls"
          sbt "; project restcontroller; coverageAggregate; coveralls"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}