name: Scala CI

on:
  push:
    branches:
      - main
      - 'SARCH-*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: compile
        run: sbt compile
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get into SBT interactive mode
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: sbt
      - name: run tests on dicecup
        run: dicecup / test
      - name: create coverageReport
        run: dicecup / coverageReport
      - name: run coverageAggregate
        run: dicecup / coverageAggregate
      - name: Export Coverage
        run: dicecup / coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}